# TCL File Generated by Component Editor 17.1
# Sun Jun 27 14:35:00 CEST 2021
# DO NOT MODIFY


# 
# i2s_clkctrl_api "i2s_clkctrl_apb" v1.7
#  2021.06.27.14:35:00
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module i2s_clkctrl_api
# 
set_module_property DESCRIPTION ""
set_module_property NAME i2s_clkctrl_api
set_module_property VERSION 1.7
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME i2s_clkctrl_apb
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2s_clkctrl_apb
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2s_clkctrl_apb.v VERILOG PATH i2s_clkctrl_apb.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point apb_slave
# 
add_interface apb_slave apb end
set_interface_property apb_slave associatedClock clock
set_interface_property apb_slave associatedReset reset
set_interface_property apb_slave ENABLED true
set_interface_property apb_slave EXPORT_OF ""
set_interface_property apb_slave PORT_NAME_MAP ""
set_interface_property apb_slave CMSIS_SVD_VARIABLES ""
set_interface_property apb_slave SVD_ADDRESS_GROUP ""

add_interface_port apb_slave paddr paddr Input 5
add_interface_port apb_slave penable penable Input 1
add_interface_port apb_slave pwrite pwrite Input 1
add_interface_port apb_slave psel psel Input 1
add_interface_port apb_slave prdata prdata Output 32
add_interface_port apb_slave pready pready Output 1
add_interface_port apb_slave pwdata pwdata Input 32


# 
# connection point ext_clk48_clkin
# 
add_interface ext_clk48_clkin clock end
set_interface_property ext_clk48_clkin clockRate 0
set_interface_property ext_clk48_clkin ENABLED true
set_interface_property ext_clk48_clkin EXPORT_OF ""
set_interface_property ext_clk48_clkin PORT_NAME_MAP ""
set_interface_property ext_clk48_clkin CMSIS_SVD_VARIABLES ""
set_interface_property ext_clk48_clkin SVD_ADDRESS_GROUP ""

add_interface_port ext_clk48_clkin ext_clk48_clkin clk Input 1


# 
# connection point ext_clk44_clkin
# 
add_interface ext_clk44_clkin clock end
set_interface_property ext_clk44_clkin clockRate 0
set_interface_property ext_clk44_clkin ENABLED true
set_interface_property ext_clk44_clkin EXPORT_OF ""
set_interface_property ext_clk44_clkin PORT_NAME_MAP ""
set_interface_property ext_clk44_clkin CMSIS_SVD_VARIABLES ""
set_interface_property ext_clk44_clkin SVD_ADDRESS_GROUP ""

add_interface_port ext_clk44_clkin ext_clk44_clkin clk Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock ""
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit ext_AUD_DACLRCLK ext_AUD_DACLRCLK Bidir 1
add_interface_port conduit ext_AUD_BCLK ext_AUD_BCLK Bidir 1
add_interface_port conduit ext_shift_bclk ext_shift_bclk Output 1
add_interface_port conduit ext_AUD_ADCLRCLK ext_AUD_ADCLRCLK Bidir 1


# 
# connection point ext_mclk
# 
add_interface ext_mclk clock start
set_interface_property ext_mclk associatedDirectClock ""
set_interface_property ext_mclk clockRate 0
set_interface_property ext_mclk clockRateKnown false
set_interface_property ext_mclk ENABLED true
set_interface_property ext_mclk EXPORT_OF ""
set_interface_property ext_mclk PORT_NAME_MAP ""
set_interface_property ext_mclk CMSIS_SVD_VARIABLES ""
set_interface_property ext_mclk SVD_ADDRESS_GROUP ""

add_interface_port ext_mclk ext_mclk clk Output 1


# 
# connection point ext_shift_clk
# 
add_interface ext_shift_clk clock start
set_interface_property ext_shift_clk associatedDirectClock ""
set_interface_property ext_shift_clk clockRate 0
set_interface_property ext_shift_clk clockRateKnown false
set_interface_property ext_shift_clk ENABLED true
set_interface_property ext_shift_clk EXPORT_OF ""
set_interface_property ext_shift_clk PORT_NAME_MAP ""
set_interface_property ext_shift_clk CMSIS_SVD_VARIABLES ""
set_interface_property ext_shift_clk SVD_ADDRESS_GROUP ""

add_interface_port ext_shift_clk ext_shift_clk clk Output 1

