# TCL File Generated by Component Editor 17.1
# Tue Jun 29 19:31:48 CEST 2021
# DO NOT MODIFY


# 
# holosynth_audio "holosynth_audio" v1.0
# Michael Brown 2021.06.29.19:31:48
# uio jack audio interface
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module holosynth_audio
# 
set_module_property DESCRIPTION "uio jack audio interface"
set_module_property NAME holosynth_audio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols/Audio & Video"
set_module_property AUTHOR "Michael Brown"
set_module_property DISPLAY_NAME holosynth_audio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL holosynth_audio
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file holosynth_audio.v VERILOG PATH holosynth_audio.v TOP_LEVEL_FILE
add_fileset_file audio_fifo.qip OTHER PATH audio_fifo.qip
add_fileset_file audio_mux.v VERILOG PATH audio_mux.v
add_fileset_file syncro_2.v VERILOG PATH syncro_2.v
add_fileset_file holosynth_audio_hw.tcl OTHER PATH holosynth_audio_hw.tcl


# 
# parameters
# 
add_parameter ADDRESS_WIDTH INTEGER 3
set_parameter_property ADDRESS_WIDTH DEFAULT_VALUE 3
set_parameter_property ADDRESS_WIDTH DISPLAY_NAME ADDRESS_WIDTH
set_parameter_property ADDRESS_WIDTH TYPE INTEGER
set_parameter_property ADDRESS_WIDTH UNITS None
set_parameter_property ADDRESS_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESS_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 8
set_parameter_property DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter IRQ_EN INTEGER 0
set_parameter_property IRQ_EN DEFAULT_VALUE 0
set_parameter_property IRQ_EN DISPLAY_NAME IRQ_EN
set_parameter_property IRQ_EN TYPE INTEGER
set_parameter_property IRQ_EN UNITS None
set_parameter_property IRQ_EN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IRQ_EN HDL_PARAMETER true
add_parameter FIFO_WIDTH INTEGER 6
set_parameter_property FIFO_WIDTH DEFAULT_VALUE 6
set_parameter_property FIFO_WIDTH DISPLAY_NAME FIFO_WIDTH
set_parameter_property FIFO_WIDTH TYPE INTEGER
set_parameter_property FIFO_WIDTH UNITS None
set_parameter_property FIFO_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_WIDTH HDL_PARAMETER true
add_parameter AUD_BIT_DEPTH INTEGER 24
set_parameter_property AUD_BIT_DEPTH DEFAULT_VALUE 24
set_parameter_property AUD_BIT_DEPTH DISPLAY_NAME AUD_BIT_DEPTH
set_parameter_property AUD_BIT_DEPTH TYPE INTEGER
set_parameter_property AUD_BIT_DEPTH UNITS None
set_parameter_property AUD_BIT_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AUD_BIT_DEPTH HDL_PARAMETER true


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group interfaces
set_module_assignment embeddedsw.dts.name generic-uio
set_module_assignment embeddedsw.dts.params.address_width 3
set_module_assignment embeddedsw.dts.params.data_width 8
set_module_assignment embeddedsw.dts.vendor holotr


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_address address Input ADDRESS_WIDTH
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_readdata readdata Output DATA_WIDTH
add_interface_port slave slave_writedata writedata Input DATA_WIDTH
add_interface_port slave slave_chipselect chipselect Input 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point slv_irq
# 
add_interface slv_irq interrupt end
set_interface_property slv_irq associatedAddressablePoint ""
set_interface_property slv_irq associatedClock clock
set_interface_property slv_irq associatedReset reset
set_interface_property slv_irq bridgedReceiverOffset ""
set_interface_property slv_irq bridgesToReceiver ""
set_interface_property slv_irq ENABLED true
set_interface_property slv_irq EXPORT_OF ""
set_interface_property slv_irq PORT_NAME_MAP ""
set_interface_property slv_irq CMSIS_SVD_VARIABLES ""
set_interface_property slv_irq SVD_ADDRESS_GROUP ""

add_interface_port slv_irq slave_irq irq Output 1


# 
# connection point pin
# 
add_interface pin conduit end
set_interface_property pin associatedClock clock
set_interface_property pin associatedReset ""
set_interface_property pin ENABLED true
set_interface_property pin EXPORT_OF ""
set_interface_property pin PORT_NAME_MAP ""
set_interface_property pin CMSIS_SVD_VARIABLES ""
set_interface_property pin SVD_ADDRESS_GROUP ""

add_interface_port pin con_int_in con_int_in Input 1
add_interface_port pin con_xxxx_zero con_xxxx_zero Input 1
add_interface_port pin con_xxxx_top con_xxxx_top Input 1
add_interface_port pin con_lrck con_lrck Input 1
add_interface_port pin con_run con_run Input 1
add_interface_port pin con_lsound_in con_lsound_in Input AUD_BIT_DEPTH
add_interface_port pin con_rsound_in con_rsound_in Input AUD_BIT_DEPTH
add_interface_port pin con_trig con_trig Output 1
add_interface_port pin con_i2s_enable con_i2s_enable Output 1

