# TCL File Generated by Component Editor 17.1
# Tue Jun 29 19:33:22 CEST 2021
# DO NOT MODIFY


# 
# audio_i2s_timing_gen "audio_i2s_timing_gen" v1.0
#  2021.06.29.19:33:22
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module audio_i2s_timing_gen
# 
set_module_property DESCRIPTION ""
set_module_property NAME audio_i2s_timing_gen
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME audio_i2s_timing_gen
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL audio_i2s_timing_gen
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file audio_i2s_timing_gen.v VERILOG PATH audio_i2s_timing_gen.v TOP_LEVEL_FILE
add_fileset_file audio_clock_generator.v VERILOG PATH audio_clock_generator.v
add_fileset_file clk_divider.v VERILOG PATH clk_divider.v
add_fileset_file syncro2_1.v VERILOG PATH syncro2_1.v
add_fileset_file audio_i2s_timing_gen_hw.tcl OTHER PATH audio_i2s_timing_gen_hw.tcl


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset reset
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit ext_AUD_DACLRCLK ext_aud_daclrclk Output 1
add_interface_port conduit playback_lrclk playback_lrclk Output 1
add_interface_port conduit playback_bclk playback_bclk Output 1
add_interface_port conduit ext_shift_clk ext_shift_clk Output 1
add_interface_port conduit ext_AUD_BCLK ext_aud_bclk Output 1

